### ISSUE TITLE
Get pos/line numbers in language

### ISSUE THREAD

**Issue by purpleidea** [martian-lang/martian#12]
In the language you use goyacc which is wonderful: https://github.com/martian-lang/martian/blob/9a44a92ae0f7de22e61753a2afcd00f32ec34c54/martian/syntax/grammar.y

I was wondering if you knew of how to get useful position and line numbers into the AST, so that each member there could know where an error was for example.

Thanks!

**Comment by adam-azarchs** [comment]
Ast nodes have that information but it isn't currently exported through the public API.  Internally, that's used for error reporting e.g. by AstError: https://github.com/martian-lang/martian/blob/master/martian/syntax/errors.go.  There's a few weird edge cases where positioning information isn't exactly correct, but it's been getting much better...

If there's a good use case for exposing that information publicly then that's an easy change to make.

**Comment by purpleidea** [comment]
@adam-azarchs Do you know how goyacc populates this information? I'm having trouble finding it in your source.

**Comment by adam-azarchs** [comment]
`goyacc` doesn't do it on its own.  The logic for tracking position is [in the lexer](https://github.com/martian-lang/martian/blob/master/martian/syntax/lexer.go#L61).  There might be a better way to do things out there.

**Comment by adam-azarchs** [comment]
Since there do not appear to be any further questions here, I'm going to close this issue.
