### ISSUE TITLE
specifying threads/memory for a 1 chunk stage

### ISSUE THREAD

**Issue by wheaton5** [martian-lang/martian#4]
What I have been doing is doing a split/main/join and setting up the options in the split, and passing on the join. Is this the standard way of doing this or is there a way to do that without a split/join?

**Comment by adam-azarchs** [comment]
This feature is implemented in Martian 3.0, coming soon...

**Comment by adam-azarchs** [comment]
If you build martian yourself, you can now get this feature.  See the commit message for https://github.com/martian-lang/martian/commit/44925776ff5c5ba5e16a21f72d4d541a47ab6950 for examples of how it's used.
