### ISSUE TITLE
add mrp pid to mrp gui

### ISSUE THREAD

**Issue by wheaton5** [martian-lang/martian#5]
Without MRV I don't have a mapping of mrp process id's to the mrp guis. I need this sometimes when I want to restart from an earlier stage (assuming all the input files are still there, i can just kill the mrp, delete the stages I don't want, then i can rerun mrp on the same directory and it starts from the last completed stage).

In any case, I now have a bunch of failed pipestances and gui's that I want to keep running but i want to clean up my failed mrp processes so i need the pids.

**Comment by adam-azarchs** [comment]
PID already there, in the third line in the top-level detail, e.g.
```
User | user@10xgenomics.com, PID=25564
```

**Comment by wheaton5** [comment]
Could this be new? I don't see this. The first detail lines are State, FQname, Path, Python, Sweeps

**Comment by adam-azarchs** [comment]
You are looking at the stage detail, not the top level detail.

**Comment by adam-azarchs** [comment]
See https://github.com/martian-lang/martian/blob/master/web/martian/templates/graph.pug#L58
