### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by olavurmortensen** [martian-lang/martian#7]
Just wondering whether Python 3 support / compatibility is planned, and if not if it could be implemented. I think this is usually very simple.

I usually work in a Python 3 environment and program in Python 3. Would be very nice to be able to use Martian with Python 3.

**Comment by adam-azarchs** [comment]
This is certainly on our radar, although we don't have immediate plans.  I have not had a chance to look at the extent to which the python adapter would need to be updated to support this, but I wouldn't expect it to be that major.

**Comment by adam-azarchs** [comment]
With Python 2 now having an [official end-of-life date](https://www.python.org/dev/peps/pep-0373/#id2), the priority for this issue is increasing.  We'll try to get it in for the 3.2 release milestone - I can't think of anything higher priority.

**Comment by adam-azarchs** [comment]
Fixed with 5a8a16bb8a648e7b2d92cc32a9ba48fbc6600de2.
