### ISSUE TITLE
MRO_DISK_SPACE_CHECK

### ISSUE THREAD

**Issue by ascendo** [martian-lang/martian#9]
Hello,
During the processing Supernova assembler, It crashed with a lack of space.
I secured the space and tried to run again.
But stuck in error.

I set the environment MRO_DISK_SPACE_CHECK=disable on my .bashrc.
But it still making error message.

Where can I put MRO_DISK_SPACE_CHECK=disable ?
Thanks

########
Log message:
/home/ascendo_u/data/J_56x/ASSEMBLER_CS has only 9088kB remaining space available.
To ignore this error, set MRO_DISK_SPACE_CHECK=disable in your environment.

Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

Saving pipestance info to J_56x/J_56x.mri.tgz
For assistance, upload this file to 10x Genomics by running:

supernova upload <your_email> J_56x/J_56x.mri.tgz

**Comment by adam-azarchs** [comment]
The command you need in your `.bashrc` or `.bash_profile` is `export MRO_DISK_SPACE_CHECK=disable`.  Without `export` bash only applies the environment variable to commands on the same line. You also need to make sure you `source .bashrc` or `source .bash_profile` after editing it.  Alternatively you can run `MRO_DISK_SPACE_CHECK=disable supernova ...` to set it just for that command.

**Comment by ascendo** [comment]
Of course, I did source my bashrc with export.


![image](https://user-images.githubusercontent.com/907041/47466150-d7354100-d7a4-11e8-87d1-4bd9d6321480.png)

**Comment by ascendo** [comment]
![image](https://user-images.githubusercontent.com/907041/47466235-2a0ef880-d7a5-11e8-91af-546b41f21d2a.png)
